<template>
  <div class="form">
    <form @submit.prevent="sendEmail">
      <div class="formFirst">
        <span>
          <label for="name">Your name</label>
          <input
            required
            aria-required="required*"
            v-model="name"
            name="name"
            id="formName"
            type="text"
            placeholder="required*"
            aria-placeholder="required*"
          />
        </span>
        <span>
          <label for="email">Your email</label>
          <input
            name="email"
            required
            aria-required="required*"
            v-model="email"
            id="formEmail"
            type="text"
            placeholder="required*"
            aria-placeholder="required*"
          />
        </span>
        <span>
          <img
            @click="slideForm()"
            src="img/arrow.png"
            alt="button for message"
          />
        </span>
      </div>
      <div class="formSecond">
        <span>
          <label for="message">Your Message</label>
          <textarea
            name="message"
            v-model="message"
            required
            aria-required="required*"
            id="formMsg"
            cols="30"
            rows="10"
            maxlength="260"
            placeholder="required*"
            aria-placeholder="required*"
          ></textarea>
          <input type="submit" value="Send" />
        </span>
      </div>
    </form>
    <div :class="{ sent: emailSent }" class="sentMsg">
      <p v-if="emailSent">{{ sent_message }}</p>
      <router-link to="/">Back</router-link>
    </div>
  </div>
</template>

<script>
import emailjs from "emailjs-com";

export default {
  // Define the prop being carried over from a different component/vue
  props: ["sent_message"],

  data() {
    return {
      // emailSent to false means that the email hasn't sent yet, and that the confirmation message isn't displayed
      emailSent: false,

      // Empty strings to be filled by the person filling the contact form
      name: "",
      email: "",
      message: "",

      // From us!
      from_name: "AP Creative",
    };
  },

  methods: {
    sendEmail(e) {
      // Attempt to use a template generated by our email service
      // using our unique key
      //TODO: Whitelist the domain as the only one that emails can be sent from
      try {
        emailjs.sendForm(
          // keys
          "service_4u1dwzc",
          "template_db6sbtz",

          // e.target references the person using the form
          e.target,
          "user_yM5mWxzyQShYcauGsoWXB",

          // Setting the email strings to the recently filled data strings
          {
            name: this.name,
            email: this.email,
            message: this.message,
            from_name: this.from_name,
          },
          // Set emailSent to true if the email goes through
          (this.emailSent = true)
        );

        // Hide the title, tagline and form
        document.querySelector(".contTitle").classList.add("hide");
        document.querySelector(".contTag").classList.add("hide");
        document.querySelector("form").classList.add("hide");
      } catch (err) {
        // If there are any errors, catch them and log them
        console.log(err);
      }
      // After everything is processed, regardless if the email was sent,
      // empty the data that was inputted by the user and set it as blank
      (this.name = ""), (this.email = ""), (this.message = "");
    },

    slideForm() {
      let x = document.getElementsByName("name")[0],
        y = document.getElementsByName("email")[0],
        formFirst = document.querySelector(".formFirst"),
        formSec = document.querySelector(".formSecond");

      // Check if the user has put content into the name and email fields
      if (x.value.trim().length == 0 || y.value.trim().length == 0) {
        // If there was no content, send an alert saying to fill them in
        alert("Please fill in form");
      } else {
        // Otherwise, log the confirmation and reveal the next piece of the form
        console.log("success");
        formFirst.classList.add("slideLeft");
        formSec.classList.add("slideLeft");
      }
    },
  },
};
</script>

<style></style>
